import numpy as np
import cv2
import glob

# 1. DEFINE THE BOARD PARAMETERS
# IMPORTANT: Count the INTERNAL VERTICES (where the black squares intersect).
# Do not count the outer squares. For example, a classic board is usually 9x6.
internal_columns = 7
internal_rows = 7

# Termination criteria to refine pixel coordinates (standard parameters, do not modify)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# Prepare 3D real-world object points mapping: (0,0,0), (1,0,0), (2,0,0) ...
objp = np.zeros((internal_rows * internal_columns, 3), np.float32)
objp[:, :2] = np.mgrid[0:internal_columns, 0:internal_rows].T.reshape(-1, 2)

# Lists to store 3D real-world coordinates and 2D image plane coordinates
points_3d = [] 
points_2d = [] 

# 2. LOAD THE PHOTOS
# Make sure you have a folder called 'calibration_photos' with your pictures
# This must match the folder generated by Photos_For_Data.py
images = glob.glob('calibration_photos/*.jpg')

print(f"Searching for chessboards in {len(images)} images...")

for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Find the geometric chessboard corners
    ret, corners = cv2.findChessboardCorners(gray, (internal_columns, internal_rows), None)

    # If corners are successfully identified, store the corresponding points
    if ret == True:
        points_3d.append(objp)
        
        # Refine pixel coordinates to sub-pixel accuracy for maximum precision
        corners2 = cv2.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
        points_2d.append(corners2)
        
        # Optional: Draw and display the detected corners for visual verification
        cv2.drawChessboardCorners(img, (internal_columns, internal_rows), corners2, ret)
        cv2.imshow('Finding corners', img)
        cv2.waitKey(500)

cv2.destroyAllWindows()

# 3. CALCULATE CALIBRATION MATRIX
print("Computing the camera calibration matrix...")
ret, cameraMatrix, distCoeffs, rvecs, tvecs = cv2.calibrateCamera(points_3d, points_2d, gray.shape[::-1], None, None)

print("\n--- RESULTS TO COPY INTO YOUR MAIN PROGRAM ---")
print("\ncameraMatrix = np.array(")
print(repr(cameraMatrix))
print(")")
print("\ndistCoeffs = np.array(")
print(repr(distCoeffs))
print(")")